### PR TITLE
Enable maximize/minimize projection editor on edit screen.

### PR DESCRIPTION
**Pull request by mjgpy3**
Please let me know your thoughts!

Here's a gif showing the change
max-min-projection-edit

If you like this, do you think it should be added to the query-tab editor as well?

### CODE REVIEW

**Comment by hayley-jean** [comment]
I think this is quite useful 👍

**Comment by pgermishuys** [comment]
This looks good. I think it would be good to add this to the query editor to remain consistent throughout the UI.

**Comment by pgermishuys** [comment]
Thanks for the amazing work so far @mjgpy3

**Comment by mjgpy3** [comment]
@hayley-jean and @pgermishuys thank you for the feedback. I will add this to the query view shortly.

**Comment by gregoryyoung** [comment]
I like it!

**Comment by mjgpy3** [comment]
Latest commit(s) add maximize/minimize to query editor. Here's what it looks like.

max-min-query-edit

**Comment by pgermishuys** [comment]
Ah! I was about to ask about that!
This looks good to me and a great addition!

**Pull request merged**
