### PR TITLE
Make it easy to add new events that are similar to existing events.

### PR DESCRIPTION
**Pull request by mjgpy3**
Let me know your thoughts!

add-new-event-like-this

### CODE REVIEW

**Comment by mjgpy3** [comment]
I'm not sure I'm fond of the wording "Add New Like This." Thoughts?

**Comment by pgermishuys** [comment]
What about `New event based on this`

**Comment by mjgpy3** [comment]
@pgermishuys I can dig that, especially since there aren't a lot of actions already on this page. @Narvalex do you have an alternative suggestion?

**Comment by Narvalex** [comment]
I appreciate @pgermishuys suggestion, but I think that your wording "Add new like this" is short and clear.

**Comment by pgermishuys** [comment]
Thanks for the input @Narvalex. Let's make it so @mjgpy3. Thanks again for the great work in the UI.

**Comment by mjgpy3** [comment]
@pgermishuys done and squashed.

**Pull request merged**
