### PR TITLE
Allow easy copying of projection name.

### PR DESCRIPTION
**Pull request by mjgpy3**
I noticed a co-worker couldn't copy a projection name because the grid
reloads rapidly enough that any highlighting would be undone before a
copy could be made.

Here's me trying to copy a projection name
difficult-to-copy-projection-name

Here's what the new functionality looks like
copy-projection-name-button

Let me know your thoughts!

### CODE REVIEW

**Comment by mjgpy3** [comment]
(sorry if the red error is confusing. The projection named `broken` actually works, the one with the longer name is, in fact, broken thus the red error).

**Comment by mjgpy3** [comment]
Hey @pgermishuys, could you provide some feedback as to why this was closed?

**Comment by pgermishuys** [comment]
This was closed because the 4.0.3 branch has been removed. This PR can be opened again against the 4.0.4 branch if that's ok with you.

**Comment by mjgpy3** [comment]
@pgermishuys great! Thank you.

**Pull request closed without merging**
