### PR TITLE
Scavenge log changes

### PR DESCRIPTION
**Pull request by lscpike**
This adds support for the new features added in following PRs:
- https://github.com/EventStore/EventStore/pull/1632
- https://github.com/EventStore/EventStore/pull/1637
- https://github.com/EventStore/EventStore/pull/1638

### CODE REVIEW

**Comment by riccardone** [comment]
@lscpike I'm reviewing this PR. 
I can see the Cancel button and it's working stopping the running Scavenge. 
I wonder what could be done to re-start a stopped Scavenge operation. 
I guess that you can retrieve the completed chunk number and then it should be possible to add a button when the scavenge has been stopped with the http request. 
Do you agree? I will create an issue to implement that later

**Comment by lscpike** [comment]
Yeah that works. I implemented a PowerShell script that scans the scavenge
log for the last scavenged chunk number. You can probably implement the
same in the UI very easily.

**Comment by riccardone** [comment]
@lscpike I've just merged and solved the conflicts. This PR works as expected, thank you!
This PR can be merged after we have merged the EventStore->Scavenge_Index
https://github.com/EventStore/EventStore/pull/1638

**Comment by ChrisChinchilla** [comment]
Let me now when this is done as I also need to add to docs :)

**Comment by riccardone** [comment]
@ChrisChinchilla this PR is completed and it does not need anything else other than merge. I have just open a new Issue about a Start button that will be eventually implemented in a new PR

**Pull request merged**
