### PR TITLE
User friendly notifications using Toastr.

### LINKED ISSUE #20: User friendly notifications
We need to remove the popups and implement a decent notification system.

### PR DESCRIPTION
**Pull request by pgermishuys**
Include the use of Toastr Notifications in the UI.

Here are a couple of samples of what the notifications look like.

image

image

Fixes #20

### CODE REVIEW

**Comment by pgermishuys** [comment]
Here is a list of possible notifications that we might display.
I might have missed a couple here and there, but it should give us a good idea of the kinds of notifications we need user acknowledgement and which don't

## Admin
**Get Subsystems**
* Error : Could not get subsystems

**Scavenge**
* Error : Scavenge failed
* Info : Ok

**Shutdown**
* Info : Server Shutdown

## Dashboard
**Get Dashboard Stats**
* Error : An error occurred

## Subscriptions
**Get Subscriptions**
* Error : An error occurred

## Projections

**New Projection**
* Warning : Please fix all validation errors (new projection)
* Error : Couldn't create a new standard projection

**Update Projection**
* Error : Projection not updated
* Info : Projection Updated

**Delete Projection**
* Error : Projection not removed
* Info : Projection removed

**Reset Projection**
* Error : Reset failed
* Info : Projection reseted

**Start Projection**
* Error : Projection could not be started
* Info : Projection started

**Stop Projection**
* Error : Projection could not be stopped
* Info : Projection stopped

**Edit Projection**
* Error : Projection does not exist or is inaccessible

**Disable All Projections**
* Error : Disable all failed
* Info : All projections disabled

**Enable All Projections**
* Error : Enable all failed
* Info : All projections enabled

## Queries
**Create Query**
* Error : Couldn't create new query

**Enable Query**
* Error : Could not start query

**Update Query**
* Error : Query not updated

## Streams
**Get ACL**
* Error : could not load metadata for stream

**Update ACL**
* Info : ACL Updated

**View events (polling)**
* Error : stream does not exist

## Authentication

**Sign In**
* Warning : Please fix all validation errors
* Warning : Server does not exist or wrong user data

## User Administration

**Disabling a user**
* Warning : User already disabled
* Error : User not disabled
* Info : User disabled

**Delete user**
* Error : User not deleted
* Info : User deleted 

**Get User**
* Error : User does not exist or you do not have permission

**Reset Password**
* Error : Password not reseted
* Info : Password reseted

**List of Users**
* Error : Cannot get list of users

**Edit User**
* Warning : Please fix all validation errors
* Info : User updated

**Enabling a user**
* Warning : User already enabled
* Info : User enabled

**Reset Password**
* Warning : Please fix all validation errors
* Info : Password Reseted 

**New User**
* Warning : Please fix all validation errors

**Comment by jen20** [comment]
:+1:

**Comment by danleech** [comment]
Great work!

I’m sure the names error/info/warning come from Toastr, but I think for our own nomenclature we should adopt success/warning/failure/info (green, amber, red, blue). I think it will help us determine which style to apply to future notifications.

The only one I might question is “Server does not exist or wrong user data.” I could conceive of that being a failure more than a warning.

**Comment by jen20** [comment]
:+1: great work guys!

**Pull request merged**
