### PR TITLE
Resolve #161. Allow users to get projection state by a partition.

### LINKED ISSUE #161: Way to get projection state for partition?
Is there a way, from a specific projection's view, to get a projection's state for a particular partition?

If not, is this a desirable feature?

Currently when I want the answer I use an HTTP client or copy the projection into the query window and modify it to get rid of partition info (e.g. replace `fromCategory().forEachStream()` with just `.fromStream('stream-i-care-about')`).

### PR DESCRIPTION
**Pull request by mjgpy3**
By default it looks like this
projection-partition-default

After entering an existing partition (and once the poll hits) it looks like
projection-partition-entered

It immediately clears when the partition is changed so that it's evident when it's updating.

Let me know your thoughts!

### CODE REVIEW

**Comment by pgermishuys** [comment]
Functionaly it looks ok. We can likely cover the aesthetics in another PR. This is because it looks like the Results and State is floating and doesn't belong.

**Comment by mjgpy3** [comment]
@pgermishuys I agree it doesn't look too pretty. What do you think would make it look nicer? I wanted to throw the input below the state header but there's already little real-estate in the corner.

**Comment by pgermishuys** [comment]
Give me a minute to do something quickly and let me know what you think.

**Comment by pgermishuys** [comment]
I had something like this in mind. The tables require a tbody tag for the style to come into affect and this ensures that some consistency is maintained throughout the UI.

What do you think?

image

**Comment by mjgpy3** [comment]
@pgermishuys :+1: that looks really nice!

**Comment by mjgpy3** [comment]
@pgermishuys I hope you don't mind, I took a shot at that image's style here's what it looks like in the latest commit

better-format

**Pull request merged**
