### PR TITLE
Query this stream

### PR DESCRIPTION
**Pull request by mjgpy3**
Same as #158 except targeting the current release.

### CODE REVIEW

**Comment by pgermishuys** [comment]
Same as with the other PR. It appears that the PR branch hasn't been rebased off of the latest release branch as there are commits that don't belong in here.

**Comment by mjgpy3** [comment]
@pgermishuys sorry about that. I cherry-picked the appropriate commit for this change.

**Comment by mjgpy3** [comment]
@hayley-jean, thank you for the feedback! I'll make that change shortly.

**Comment by mjgpy3** [comment]
@hayley-jean requested change has been made. I also squashed the commits as they were getting a little messy.

**Pull request merged**
